### ISSUE TITLE
Failed compilation due to trait not implemented

### ISSUE THREAD

**Issue by AblativeAbsolute** [Hirevo/mega-cli-rs#3]
Discovered this issue while trying to build version `v0.1.2` inside a container (`rust:1-slim-bookworm`) and with regular cargo installation.

## How to reproduce
```Dockerfile
FROM rust:1-slim-bookworm
RUN apt-get update && apt-get install -y pkg-config libssl-dev
RUN cargo install mega-cli
```
Otherwise just call `cargo install mega-cli` to reproduce.

### Error message
```
error[E0277]: `std::option::Option<std::string::String>` doesn't implement `std::fmt::Display`
  --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mega-cli-0.1.2/src/commands/auth/me.rs:53:9
   |
53 |         user.country_code,
   |         ^^^^^^^^^^^^^^^^^ `std::option::Option<std::string::String>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `std::option::Option<std::string::String>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: this error originates in the macro `format_args` which comes from the expansion of the macro `crate::info` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0277`.
error: could not compile `mega-cli` (bin "mega-cli") due to 1 previous error
error: failed to compile `mega-cli v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-installlgdlGF`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by Hirevo** [comment]
Hello, thanks for reporting this issue.  

This was due to me updating the underlying `mega` library with a minor semver update (`v0.7.4`), in order to address the bug reported in **#2**.  
I wrongly assessed that the change would not require a dedicated `mega-cli` release in order to make use of that fix.  
I've now made a new `v0.1.3` release of `mega-cli`, which fixes this compilation error.

If you wish to make your Dockerfile more resilient to similar issues in the future, you may consider adding the `--locked` flag to your `cargo install` command, like so:

```
cargo install --locked mega-cli
```

This will stick to using the exact crate versions listed in the `Cargo.lock` file, instead of optimistically updating dependencies using semver.

I'm sorry for the inconvenience, and I'll be more careful going forward when releasing updates to the `mega` library.
